### ISSUE TITLE
Config in readme incorrect/imncomplete

### ISSUE THREAD

**Issue by Pushplaybang** [wip/action#17]
Having tried to implement this action, we found first that the example had incorrect indentation, and once corrected produced errors.

our working config:

```yaml
name: Set PR review status
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  wip:
    name: Set WIP status
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@v1.0.0
```
