### ISSUE TITLE
Can't figure out how to use it

### ISSUE THREAD

**Issue by nfedyashev** [wip/action#19]
I'm trying to get this Github Action workflow to work and can't figure it out.
What I've tried:
"WIP", "wip" in pull request titles.
"wip" in branch name.
Please let me know what I'm doing wrong.

![Screenshot 2020-03-01 at 16 03 20](https://user-images.githubusercontent.com/61983/75627131-4bbc9300-5bd6-11ea-875e-48b55fafe07e.png)

"WIP (action) Pending — work in progress" stays like this forever. Details link points to the https://github.com/wip/action.

README says
>An example workflow looks like this (switch to the <> Edit new file tab when creating a new workflow and paste the code below):

I feel stupid asking this but what is "<> Edit new file tab when creating a new workflow"?
I've saved this PR as:
```
cat .github/workflows/wip_pr_label.yml                                                                                                                              master  ✱
name: WIP
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  wip:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@v1.0.0
```
